name       : pandoc-crossref
version    : 0.3.4.2
release    : 1
source     :
    - https://hackage.haskell.org/package/pandoc-crossref-0.3.4.2/pandoc-crossref-0.3.4.2.tar.gz : 6283fca01fbd54f720df89ed96e4d93b801f2786f9f39052f43627d24f896d0d
license    : GPL-2.0-only
component  : office
summary    : pandoc-crossref is a pandoc filter for numbering figures, equations, tables and cross-references to them.
description: |
    pandoc-crossref is a pandoc filter for numbering figures, equations, tables and cross-references to them.
builddeps  :
    - haskell-cabal-install
    - haskell-data-accessor-template-devel
    - haskell-data-accessor-transformers-devel
    - haskell-gitrev-devel
    - haskell-open-browser-devel
    - haskell-optparse-applicative-devel
    - haskell-roman-numerals-devel
    - haskell-temporary-devel
    - pandoc-devel
rundeps    :
    - devel:
        - haskell-data-accessor-template-devel
        - haskell-data-accessor-transformers-devel
        - haskell-gitrev-devel
        - haskell-open-browser-devel
        - haskell-optparse-applicative-devel
        - haskell-roman-numerals-devel
        - haskell-temporary-devel
        - pandoc-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
